### ISSUE TITLE
create portal not working

### ISSUE THREAD

**Issue by keinereiner** [treolabs/treopim#162]
create a new portal, will every time display an error message: Error 400: Site URL is empty
But the URL is not empty... with "http" or without... nothing work....

**Comment by keinereiner** [comment]
ok, thanks this worked. But than is the error message a little bit strange... maybe it should write: Please define the site URL on the Administration > Settings page first.

**Comment by irybachok** [comment]
@keinereiner you are welcome. We will consider changing the error message
