### ISSUE TITLE
api routes missing

### ISSUE THREAD

**Issue by bskade** [treolabs/treopim#348]
Hello,
first of all, great work. Looks very promising.
I tried some endpoints that I couldn get to work for example

/Product/{product_id}/listImages

could find the route in  application/Espo/Resources/routes.json
maybe the routes should be autogenerated by annotation/comments as the documentation

**Comment by rratsun** [comment]
Hello,
You cannot find this URL, because it is a part of the module PIM that is always installed with the system as the dependence. However, thank you for pointing out this error. It is a deprecated method and we will remove it.
