### ISSUE TITLE
Authentication against API

### ISSUE THREAD

**Issue by hgpit** [treolabs/treopim#360]
Hi,

I don't have a lot of experience with authenticating against an API via curl, so I'm wondering if someone can point me in the right direction to get started.

I created a user 'dev', password '1234', with admin privileges.

Based on https://github.com/treolabs/treopim/issues/349 I tried to connect using:

`curl --header "Espo-Authorization: $(echo -n dev:1234|base64)" --get https://treopim.mydomain.com/api/v1/App/User`

Nothing is returned. I am expecting a token.

How should I complete the authentication part?

**Comment by hgpit** [comment]
I have tried this also using a REST testing app.

I am getting this response:

404 Not Found
Date: Sun, 03 Mar 2019 11:12:02 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.2
X-Powered-By: PHP/7.3.2
X-Status-Reason: Action 'read' (GET) does not exist in controller 'App'
Content-Length: 0
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
Content-Type: text/html;charset=UTF-8

**Comment by rratsun** [comment]
Hello,

here an example of curl request
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "Espo-Authorization: YWRtaW46aWFtYWRtaW4" http://treopim.local/api/v1/App/user
