### ISSUE TITLE
Unable to update 'image' via Product API

### ISSUE THREAD

**Issue by hgpit** [treolabs/treopim#363]
Hi,

Should I be able to link a product to an image via the API? I was under the impression that every single CRUD function of TreoPIM is internally handled by the API.

I can GET https://treopim.mydomain.com/api/v1/Brand fine, so I know my basic API access is okay.
But if I try to update a product's image with:

`PUT https://treopim.mydomain.com/api/v1/Product/5c7a7ce88ba535aab`

with JSON paylod:

```
{
  "image": "5c7ac114a5529d14e"
}
```

I receive a 'HTTP/1.1 200 OK' but nothing changes in the DB table 'product_image_product'.

Am I doing it wrong, or how can I toubleshoot this?

Also, I just noticed, your API docs say the 'entityid' part of the API URL should be an integer, however the actual DB has the ID as a varchar field.

**Comment by rratsun** [comment]
Hello,
Product may have a few images. And of course one image may be used by few products. From that reason we have a Product entity related to ProductImage entity as ManytoMany(product_image_product table).
