### ISSUE TITLE
Unable to import brand by brand name via Product API

### ISSUE THREAD

**Issue by hgpit** [treolabs/treopim#364]
According to the API documentation we should be able to import a product's brand by it's brand name:

![image](https://user-images.githubusercontent.com/16598973/53721824-12830300-3e5c-11e9-9f12-8877210fbd3f.png)

We have tried doing this, and triple checking the Brand exists (by name) on our TreoPIM, but the resulting record still has an empty brand.

Is this a bug?

**Comment by rratsun** [comment]
Hello,
It's a mistake in api docs generator. We will fix it soon. You should use brandId for relating Product entity with Brand entity.
